# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(help_text='Nao use caracteres especiais: <em>40353111</em', max_length=20)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(help_text='Use o seguinte formato: <em>071999998888 ou 32220000</em>', max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='financeiro.Pessoa')),
                ('cpf', models.CharField(help_text='Use o seguinte formato: <em>xxx.xxx.xxx-xx</em>', max_length=15, primary_key=True, serialize=False)),
                ('data_nascimento', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('funcao', models.CharField(max_length=50)),
            ],
            bases=('financeiro.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='financeiro.Pessoa')),
                ('cnpj', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=45)),
            ],
            bases=('financeiro.pessoa',),
        ),
        migrations.CreateModel(
            name='ClientePessoaFisica',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PessoaFisica')),
            ],
            bases=('financeiro.pessoafisica',),
        ),
        migrations.CreateModel(
            name='ClientePessoaJuridica',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PessoaJuridica')),
            ],
            bases=('financeiro.pessoajuridica',),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PessoaJuridica')),
                ('incricao_estadual', models.CharField(max_length=20)),
                ('inscricao_municipal', models.CharField(max_length=20)),
            ],
            bases=('financeiro.pessoajuridica',),
        ),
        migrations.CreateModel(
            name='FornecedorPessoaFisica',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PessoaFisica')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.PessoaFisica')),
            ],
            bases=('financeiro.pessoafisica',),
        ),
        migrations.CreateModel(
            name='FornecedorPessoaJuridica',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PessoaJuridica')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.PessoaJuridica')),
            ],
            bases=('financeiro.pessoajuridica',),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='clientepessoajuridica',
            name='cnpj_do_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.PessoaJuridica'),
        ),
        migrations.AddField(
            model_name='clientepessoafisica',
            name='cpf_do_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.PessoaFisica'),
        ),
    ]
