# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='incricao_estadual',
            new_name='inscricao_estadual',
        ),
    ]
