# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 21:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import financeiro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaixasPagar',
            fields=[
                ('id_baixa_pagar', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=20)),
                ('disponibilidade', models.CharField(max_length=20)),
                ('data_baixa', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('residual', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BaixasReceber',
            fields=[
                ('id_baixa_receber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=20)),
                ('disponibilidade', models.CharField(max_length=20)),
                ('data_baixa', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('residual', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContasBancarias',
            fields=[
                ('id_contas_bancarias', models.IntegerField(primary_key=True, serialize=False)),
                ('classificacao', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('numero_conta', models.CharField(max_length=20)),
                ('numero_agencia', models.CharField(max_length=20)),
                ('data_saldo_inicial', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('caixa', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FormasPagamentos',
            fields=[
                ('id_forma_pagamento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentosPagar',
            fields=[
                ('id_lancamentos_pagar', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('numero_documento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentosReceber',
            fields=[
                ('id_lancamentos_receber', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('valor_titulo', models.FloatField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('numero_documento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('nome', models.CharField(default='', max_length=50)),
                ('sobrenome', models.CharField(default='', max_length=100)),
                ('endereco', models.CharField(default='', max_length=50)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('municipio', models.CharField(default='', max_length=50)),
                ('cep', models.CharField(default=' ', help_text='Nao use caracteres especiais: <em>40353111</em', max_length=20)),
                ('uf', models.CharField(default='', max_length=2)),
                ('telefone', models.CharField(default='', help_text='Use o seguinte formato: <em>071999998888 ou 32220000</em>', max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('cpf', models.CharField(help_text='Use o seguinte formato: <em>xxx.xxx.xxx-xx</em>', max_length=15, primary_key=True, serialize=False)),
                ('data_nascimento', models.DateField(default=datetime.date.today, help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('funcao', models.CharField(max_length=49)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('nome', models.CharField(default='', max_length=50)),
                ('sobrenome', models.CharField(default='', max_length=100)),
                ('endereco', models.CharField(default='', max_length=50)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('municipio', models.CharField(default='', max_length=50)),
                ('cep', models.CharField(default=' ', help_text='Nao use caracteres especiais: <em>40353111</em', max_length=20)),
                ('uf', models.CharField(default='', max_length=2)),
                ('telefone', models.CharField(default='', help_text='Use o seguinte formato: <em>071999998888 ou 32220000</em>', max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('cnpj', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoDeContas',
            fields=[
                ('id_plano_contas', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('classificacao', models.CharField(max_length=20)),
                ('tipo_conta', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('caixa', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=20)),
                ('fornecedor', models.CharField(max_length=20)),
                ('entrada_recurso', models.CharField(max_length=20)),
                ('saida_recurso', models.CharField(max_length=20)),
                ('contas_bancarias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.ContasBancarias')),
            ],
        ),
        migrations.CreateModel(
            name='Tesouraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.ContasBancarias')),
                ('conta_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.ContasBancarias')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePessoaFisica',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PessoaFisica')),
            ],
            options={
                'abstract': False,
            },
            bases=('financeiro.pessoafisica',),
        ),
        migrations.CreateModel(
            name='ClientePessoaJuridica',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PessoaJuridica')),
            ],
            options={
                'abstract': False,
            },
            bases=('financeiro.pessoajuridica',),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PessoaJuridica')),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('inscricao_municipal', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('financeiro.pessoajuridica',),
        ),
        migrations.CreateModel(
            name='FornecedorPessoaFisica',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PessoaFisica')),
                ('cliente_fpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.PessoaFisica')),
            ],
            options={
                'abstract': False,
            },
            bases=('financeiro.pessoafisica',),
        ),
        migrations.CreateModel(
            name='FornecedorPessoaJuridica',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.PessoaJuridica')),
                ('cliente_fpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.PessoaJuridica')),
            ],
            options={
                'abstract': False,
            },
            bases=('financeiro.pessoajuridica',),
        ),
        migrations.AddField(
            model_name='baixasreceber',
            name='id_forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.FormasPagamentos'),
        ),
        migrations.AddField(
            model_name='baixasreceber',
            name='id_lancamentos_receber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.LancamentosReceber'),
        ),
        migrations.AddField(
            model_name='baixaspagar',
            name='id_forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.FormasPagamentos'),
        ),
        migrations.AddField(
            model_name='baixaspagar',
            name='id_lancamentos_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.LancamentosPagar'),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.ClientePessoaJuridica'),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.Empresa'),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.FornecedorPessoaJuridica'),
        ),
        migrations.AddField(
            model_name='lancamentosreceber',
            name='cliente',
            field=models.ForeignKey(on_delete=financeiro.models.ClientePessoaFisica, related_name='+', to='financeiro.ClientePessoaJuridica'),
        ),
        migrations.AddField(
            model_name='lancamentosreceber',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.Empresa'),
        ),
        migrations.AddField(
            model_name='lancamentospagar',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.Empresa'),
        ),
        migrations.AddField(
            model_name='lancamentospagar',
            name='fornecedor',
            field=models.ForeignKey(on_delete=financeiro.models.FornecedorPessoaJuridica, related_name='+', to='financeiro.FornecedorPessoaFisica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='clientepessoajuridica',
            name='cnpj_do_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.PessoaJuridica'),
        ),
        migrations.AddField(
            model_name='clientepessoafisica',
            name='cpf_do_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.PessoaFisica'),
        ),
    ]
