# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentospagar',
            name='id_lancamentos_pagar',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificação do Lançamento a Receber'),
        ),
        migrations.AlterField(
            model_name='lancamentosreceber',
            name='id_lancamentos_receber',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificação do Lançamento a Receber'),
        ),
    ]
