# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 02:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import financeiro.models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20170425_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaixasPagar',
            fields=[
                ('id_baixa_pagar', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=20)),
                ('disponibilidade', models.CharField(max_length=20)),
                ('data_baixa', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('residual', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BaixasReceber',
            fields=[
                ('id_baixa_receber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=20)),
                ('disponibilidade', models.CharField(max_length=20)),
                ('data_baixa', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('residual', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContasBancarias',
            fields=[
                ('id_contas_bancarias', models.IntegerField(primary_key=True, serialize=False)),
                ('classificacao', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('numero_conta', models.CharField(max_length=20)),
                ('numero_agencia', models.CharField(max_length=20)),
                ('data_saldo_inicial', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('caixa', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FormasPagamentos',
            fields=[
                ('id_forma_pagamento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentosPagar',
            fields=[
                ('id_lancamentos_pagar', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('numero_documento', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.Empresa')),
                ('fornecedor', models.ForeignKey(on_delete=financeiro.models.FornecedorPessoaJuridica, related_name='+', to='financeiro.FornecedorPessoaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentosReceber',
            fields=[
                ('id_lancamentos_receber', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('valor_titulo', models.FloatField(help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>')),
                ('numero_documento', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=financeiro.models.ClientePessoaFisica, related_name='+', to='financeiro.ClientePessoaJuridica')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeContas',
            fields=[
                ('id_plano_contas', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('classificacao', models.CharField(max_length=20)),
                ('tipo_conta', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('caixa', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=20)),
                ('fornecedor', models.CharField(max_length=20)),
                ('entrada_recurso', models.CharField(max_length=20)),
                ('saida_recurso', models.CharField(max_length=20)),
                ('contas_bancarias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.ContasBancarias')),
            ],
        ),
        migrations.CreateModel(
            name='Tesouraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.ClientePessoaJuridica')),
                ('conta_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.ContasBancarias')),
                ('conta_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.ContasBancarias')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.Empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.FornecedorPessoaJuridica')),
            ],
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today, help_text='Use o seguinte formato: <em>DD/MM/AAAA</em>'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(help_text='Nao use caracteres especiais: <em>40353111</em', max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(help_text='Use o seguinte formato: <em>071999998888 ou 32220000</em>', max_length=20),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(help_text='Use o seguinte formato: <em>xxx.xxx.xxx-xx</em>', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='baixasreceber',
            name='id_forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.FormasPagamentos'),
        ),
        migrations.AddField(
            model_name='baixasreceber',
            name='id_lancamentos_receber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.LancamentosReceber'),
        ),
        migrations.AddField(
            model_name='baixaspagar',
            name='id_forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.FormasPagamentos'),
        ),
        migrations.AddField(
            model_name='baixaspagar',
            name='id_lancamentos_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financeiro.LancamentosPagar'),
        ),
    ]
