# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20170513_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'verbose_name': 'Pessoa Física'},
        ),
    ]
