# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20170510_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='pessoa_ptr',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='bairro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cep',
            field=models.CharField(default=' ', help_text='Nao use caracteres especiais: <em>40353111</em', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='endereco',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='municipio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='sobrenome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='telefone',
            field=models.CharField(default='', help_text='Use o seguinte formato: <em>071999998888 ou 32220000</em>', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='uf',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='bairro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cep',
            field=models.CharField(default=' ', help_text='Nao use caracteres especiais: <em>40353111</em', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='endereco',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='municipio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='sobrenome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='telefone',
            field=models.CharField(default='', help_text='Use o seguinte formato: <em>071999998888 ou 32220000</em>', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='uf',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
