# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20170513_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contasbancarias',
            options={'verbose_name': 'Conta Bancária', 'verbose_name_plural': 'Contas Bancária'},
        ),
    ]
